// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: mangahub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Progress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MangaId        string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,2,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *Progress) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *Progress) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *Progress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*Progress            `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressResponse) GetProgress() []*Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

var File_mangahub_proto protoreflect.FileDescriptor

const file_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x0emangahub.proto\x12\bmangahub\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"f\n" +
	"\bProgress\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x02 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"B\n" +
	"\x10ProgressResponse\x12.\n" +
	"\bprogress\x18\x01 \x03(\v2\x12.mangahub.ProgressR\bprogress2T\n" +
	"\fMangaService\x12D\n" +
	"\x0fGetUserProgress\x12\x15.mangahub.UserRequest\x1a\x1a.mangahub.ProgressResponseB\x1bZ\x19MangaHub/internal/grpc/pbb\x06proto3"

var (
	file_mangahub_proto_rawDescOnce sync.Once
	file_mangahub_proto_rawDescData []byte
)

func file_mangahub_proto_rawDescGZIP() []byte {
	file_mangahub_proto_rawDescOnce.Do(func() {
		file_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)))
	})
	return file_mangahub_proto_rawDescData
}

var file_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mangahub_proto_goTypes = []any{
	(*UserRequest)(nil),      // 0: mangahub.UserRequest
	(*Progress)(nil),         // 1: mangahub.Progress
	(*ProgressResponse)(nil), // 2: mangahub.ProgressResponse
}
var file_mangahub_proto_depIdxs = []int32{
	1, // 0: mangahub.ProgressResponse.progress:type_name -> mangahub.Progress
	0, // 1: mangahub.MangaService.GetUserProgress:input_type -> mangahub.UserRequest
	2, // 2: mangahub.MangaService.GetUserProgress:output_type -> mangahub.ProgressResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mangahub_proto_init() }
func file_mangahub_proto_init() {
	if File_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mangahub_proto_goTypes,
		DependencyIndexes: file_mangahub_proto_depIdxs,
		MessageInfos:      file_mangahub_proto_msgTypes,
	}.Build()
	File_mangahub_proto = out.File
	file_mangahub_proto_goTypes = nil
	file_mangahub_proto_depIdxs = nil
}
